#!/bin/bash

NAME="gender_novels_site"                                   # Name of the application
ROOTDIR=/home/ubuntu/gender_novels_site  	                # project directory
SOCKFILE=/home/ubuntu/run/gunicorn.sock 	                # we will communicate using this unix socket
LOGFILE=/home/ubuntu/run/logs/gunicorn_supervisor.log
NUM_WORKERS=4                                               # how many worker processes should Gunicorn spawn
WSGI_MODULE=wsgi                                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $ROOTDIR
source ../venv/bin/activate

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
chmod 777 $RUNDIR

# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec gunicorn ${WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--log-level=warning \
--log-file=$LOGFILE \
--bind 0:8000  # run directly without nginx for testing
# --bind=unix:$SOCKFILE
